# Generated by Django 6.0.4 on 2026-04-07 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identificador_sesion", models.CharField(max_length=64, unique=True)),
                (
                    "titulo",
                    models.CharField(default="Nueva conversación", max_length=120),
                ),
                ("mensaje_sistema", models.TextField()),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("actualizada_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-actualizada_en"],
            },
        ),
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("system", "Sistema"),
                            ("user", "Usuario"),
                            ("assistant", "Asistente"),
                        ],
                        max_length=16,
                    ),
                ),
                ("contenido", models.TextField()),
                ("orden", models.PositiveIntegerField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "conversacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="chat_agentes.conversacion",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "id"],
                "unique_together": {("conversacion", "orden")},
            },
        ),
    ]
